[versions]
#Core
agp = "8.13.2"
kotlin = "1.9.23"

#AndroidX Core
coreKtx = "1.13.1"
activityCompose = "1.9.0"

#Compose
composeBom = "2024.06.00"
coil = "2.6.0"
navigation = "2.7.7"

#DI
ksp = "1.9.23-1.0.20"
hilt = "2.55"
androidxHilt = "1.2.0"

#Persistence
roomCompiler = "2.6.1"
datastore = "1.1.1"

#Networking
retrofit = "2.9.0"
okhttp = "4.12.0"
moshiKotlin = "1.12.0"
rabbitmq = "5.25.0"

#Background work
workmanager = "2.9.0"
workRuntimeKtx = "2.10.0"

#Maps
mapbox = "11.11.0"

#Testing
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
junitJunit = "4.12"
uiText = "1.10.2"

[libraries]
# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#Lifecycle
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }

# Activity & Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#Navigation
androidx-compose-navigation= { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }

# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomCompiler" }

# DataStore
androidx-preferences-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Networking
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref ="coil" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name="logging-interceptor", version.ref = "okhttp" }
rabbitmq-amqp-client = { group = "com.rabbitmq", name = "amqp-client", version.ref = "rabbitmq"}

# WorkMananger
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
work-runtime = {group="androidx.work", name="work-runtime", version.ref="workmanager"}

# Mapbox
mapbox-android = { group = "com.mapbox.maps", name = "android", version.ref = "mapbox" }
mapbox-extension-compose = { group = "com.mapbox.extension", name = "maps-compose", version.ref = "mapbox" }

#Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitJunit" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

